<?php

/**
 * @file
 */

/**
 * Implements hook_cron().
 */
function webform_summary_cron() {
  $lastExecution = (int) \Drupal::state()->get('webform_summary.last_execution');
  $lastExecutionDay = date('z', $lastExecution);
  $currentDay = date('z', \Drupal::time()->getRequestTime());
  if (date('Y', \Drupal::time()->getRequestTime()) > date('Y', $lastExecution)) {
    $lastExecutionDay = -1;
  }
  if ($currentDay > $lastExecutionDay) {
    $startDate = new DateTime('1 year ago');
    $endDate = new DateTime('1 days ago');
    \Drupal::logger('webform_summary')->notice('Sending webform summaries between ' . $startDate->format('Y/m/d') . ' and  ' . $endDate->format('Y/m/d'));
    $mailer = \Drupal::service('webform_summary.mailer');
    $mailer->setStartDate($startDate);
    $mailer->setEndDate($endDate);
    $mailer->run();
    \Drupal::state()->set('webform_summary.last_execution', \Drupal::time()->getRequestTime());
  }
}

/**
 * Implements hook_mail().
 */
function webform_summary_mail($key, &$message, $params) {
  switch ($key) {
    case "webform_summary_csv":
      $settings = \Drupal::config('webform_summary.settings');
      $from = $settings->get('webform_submissions_sender');
      $message['from'] = $from;
      $message['headers']['From'] = $from;
      $message['headers']['Sender'] = $from;
      $message['headers']['Return-Path'] = $from;
      $message['subject'] = t($settings->get('webform_submissions_subject'));
      $body = (empty($settings->get('webform_submissions_body'))) ? $settings->get('webform_submissions_subject') : $settings->get('webform_submissions_body');
      $message['body'][] = t($body);
      break;
  }
}
