webform_summary.settings:
  type: config_object
  label: "Webform summary settings"
  mapping:
    webform_submissions_email:
      type: string
      label: "The webform submissions email."
    webform_submissions_sender:
      type: string
      label: "The webform sender email."
    webform_submissions_subject:
      type: string
      label: "The webform submission subject."
    webform_close_send_data:
      type: boolean
      label: "Whether to send data on close/archive/delete."
    webform_submissions_disable:
      type: boolean
      label: "Whether to disable sending emails."
